version: '3.7'
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: goodzone
    container_name: goodzone-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - goodzone
    depends_on:
      - redis

  db:
    platform: linux/x86_64 #macOS
    image: mysql:5.7
    container_name: goodzone-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      # MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - goodzone

  nginx:
    image: nginx:alpine
    container_name: goodzone-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - goodzone
    environment:
      - VIRTUAL_HOST=${GOODZONE_HOSTNAME}
      - LETSENCRYPT_HOST=${GOODZONE_HOSTNAME}
      - LETSENCRYPT_EMAIL=${GOODZONE_EMAIL}

  redis:
    image: redis:alpine
    container_name: goodzone-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./docker-compose/redis:/data
    networks:
      - goodzone

networks:
  goodzone:
    driver: bridge
